authors:
  Wcowin:
    name: Wang Kewen    # Author name
    description: Free and casual # Author description
    avatar: https://pic4.zhimg.com/80/v2-a0456a5f527c1923f096759f2926012f_1440w.webp
    # https://s1.imagehub.cc/images/2024/02/02/91a767e93d1a344e44c69936464c583e.png         # Author avatar
    