authors:
  Wcowin:
    name: Wang Kewen    # Author name
    description: Free and casual # Author description
    avatar: https://s1.imagehub.cc/images/2025/01/05/64eafdf8c27f482c7ecb83003d460d6a.webp
    # https://s1.imagehub.cc/images/2024/02/02/91a767e93d1a344e44c69936464c583e.png         # Author avatar
    